### ISSUE TITLE
Python Connector Randomly Stopped Working - Won't Connect

### ISSUE THREAD

**Issue by mbwmbw1337** [snowflakedb/snowflake-connector-python#1342]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using?

Python 3.9.13 (main, Sep  4 2022, 17:18:12) 
[Clang 13.1.6 (clang-1316.0.21.2.5)]

2. What operating system and processor architecture are you using?

macOS-13.0.1-arm64-arm-64bit

3. What are the component versions in the environment (`pip freeze`)?

```
asn1crypto==1.5.1
certifi==2022.9.24
cffi==1.15.1
charset-normalizer==2.1.1
cryptography==38.0.3
filelock==3.8.0
idna==3.4
oscrypto==1.3.0
pycparser==2.21
pycryptodomex==3.15.0
PyJWT==2.6.0
pyOpenSSL==22.1.0
pytz==2022.6
requests==2.28.1
snowflake-connector-python==2.8.2
typing_extensions==4.4.0
urllib3==1.26.12
```

4. What did you do?

```
import logging
import os

for logger_name in ['snowflake','botocore']:
	logger = logging.getLogger(logger_name)
	logger.setLevel(logging.DEBUG)
	ch = logging.FileHandler('python_connector.log')
	ch.setLevel(logging.DEBUG)
	ch.setFormatter(logging.Formatter('%(asctime)s - %(threadName)s %(filename)s:%(lineno)d - %(funcName)s() - %(levelname)s - %(message)s'))
	logger.addHandler(ch)

import snowflake.connector
snowflake_ctx = snowflake.connector.connect(
    user='username',
    account='accountname',
    password='password',
)
print(snowflake_ctx)
```

5. What did you expect to see?

Expect to connect to the platform. Same code was working for a solid 3 weeks before. Nothign changed on computer.

6. Can you set logging to DEBUG and collect the logs?

   ```
   import logging
   import os

   for logger_name in ('snowflake.connector',):
       logger = logging.getLogger(logger_name)
       logger.setLevel(logging.DEBUG)
       ch = logging.StreamHandler()
       ch.setLevel(logging.DEBUG)
       ch.setFormatter(logging.Formatter('%(asctime)s - %(threadName)s %(filename)s:%(lineno)d - %(funcName)s() - %(levelname)s - %(message)s'))
       logger.addHandler(ch)
   ```

```
snowflake.connector.errors.OperationalError: 251011: 251011: ConnectionTimeout occurred. Will be handled by authenticator

During handling of the above exception, another exception occurred:

RecursionError: maximum recursion depth exceeded while calling a Python object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/network.py", line 1018, in _request_exec
    raw_ret = session.request(
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/vendored/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/vendored/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/vendored/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/vendored/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/ssl_wrap_socket.py", line 78, in ssl_wrap_socket_with_ocsp
    from .ocsp_asn1crypto import SnowflakeOCSPAsn1Crypto as SFOCSP
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/ocsp_asn1crypto.py", line 47, in <module>
    from snowflake.connector.ocsp_snowflake import SnowflakeOCSP, generate_cache_key
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/ocsp_snowflake.py", line 81, in <module>
    ] = SFDictFileCache(
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/cache.py", line 404, in __init__
    self._load()
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/cache.py", line 482, in _load
    self._update(
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/cache.py", line 213, in _update
    other._clear_expired_entries()
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/cache.py", line 271, in _clear_expired_entries
    self._getitem(k, should_record_hits=False)
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/cache.py", line 424, in _getitem
    loaded = self._load_if_should()
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/cache.py", line 542, in _load_if_should
    return self._load()
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/cache.py", line 482, in _load
    self._update(
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/cache.py", line 204, in _update
    self._clear_expired_entries()
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/cache.py", line 271, in _clear_expired_entries
    self._getitem(k, should_record_hits=False)
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/cache.py", line 424, in _getitem
    loaded = self._load_if_should()
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/cache.py", line 542, in _load_if_should
    return self._load()
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/cache.py", line 482, in _load
    self._update(
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/cache.py", line 204, in _update
    self._clear_expired_entries()
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/cache.py", line 271, in _clear_expired_entries
    self._getitem(k, should_record_hits=False)
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/cache.py", line 424, in _getitem
    loaded = self._load_if_should()
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/cache.py", line 542, in _load_if_should
    return self._load()
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/cache.py", line 482, in _load
    self._update(
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/cache.py", line 204, in _update
    self._clear_expired_entries()
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/cache.py", line 271, in _clear_expired_entries
    self._getitem(k, should_record_hits=False)
**** ABOUT 65,000 LINES OF REPEATING TEXT ****
    return self._load()
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/cache.py", line 482, in _load
    self._update(
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/cache.py", line 204, in _update
    self._clear_expired_entries()
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/cache.py", line 271, in _clear_expired_entries
    self._getitem(k, should_record_hits=False)
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/cache.py", line 424, in _getitem
    loaded = self._load_if_should()
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/cache.py", line 542, in _load_if_should
    return self._load()
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/cache.py", line 482, in _load
    self._update(
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/cache.py", line 204, in _update
    self._clear_expired_entries()
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/cache.py", line 271, in _clear_expired_entries
    self._getitem(k, should_record_hits=False)
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/cache.py", line 424, in _getitem
    loaded = self._load_if_should()
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/cache.py", line 542, in _load_if_should
    return self._load()
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/cache.py", line 482, in _load
    self._update(
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/cache.py", line 204, in _update
    self._clear_expired_entries()
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/cache.py", line 271, in _clear_expired_entries
    self._getitem(k, should_record_hits=False)
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/cache.py", line 424, in _getitem
    loaded = self._load_if_should()
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/cache.py", line 542, in _load_if_should
    return self._load()
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/cache.py", line 482, in _load
    self._update(
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/cache.py", line 204, in _update
    self._clear_expired_entries()
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/cache.py", line 271, in _clear_expired_entries
    self._getitem(k, should_record_hits=False)
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/cache.py", line 424, in _getitem
    loaded = self._load_if_should()
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/cache.py", line 542, in _load_if_should
    return self._load()
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/cache.py", line 482, in _load
    self._update(
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/cache.py", line 204, in _update
    self._clear_expired_entries()
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/cache.py", line 271, in _clear_expired_entries
    self._getitem(k, should_record_hits=False)
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/cache.py", line 424, in _getitem
    loaded = self._load_if_should()
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/cache.py", line 542, in _load_if_should
    return self._load()
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/cache.py", line 482, in _load
    self._update(
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/cache.py", line 204, in _update
    self._clear_expired_entries()
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/cache.py", line 271, in _clear_expired_entries
    self._getitem(k, should_record_hits=False)
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/cache.py", line 424, in _getitem
    loaded = self._load_if_should()
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/cache.py", line 542, in _load_if_should
    return self._load()
  File "/Users/michael/Source/AWS/testproject/venv/lib/python3.9/site-packages/snowflake/connector/cache.py", line 480, in _load
    with open(self.file_path, "rb") as r_file:
RecursionError: maximum recursion depth exceeded while calling a Python object
2022-11-22 18:38:25,096 - MainThread network.py:1152 - _use_requests_session() - DEBUG - Session status for SessionPool 'XXX.snowflakecomputing.com', SessionPool 0/1 active sessions
2022-11-22 18:38:25,096 - MainThread connection.py:1118 - __authenticate() - DEBUG - Continuing authenticator specific timeout handling
```

**Comment by mbwmbw1337** [comment]
The issue was resolved by clearing the snowflake cache directory (/Users/michael/Library/Caches/Snowflake) -- I highly recommend that the showflake team build a fix for this into the system. The connection would not fail at all would stay open for hours.

**Comment by sfc-gh-aling** [comment]
thanks for the reaching out and sharing us with the stack, we will investigate this as soon as possible

**Comment by mbwmbw1337** [comment]
The workaround, for now, is below. I have validated that this only happens in certain instances and the entire connect hangs indefinitely if a file in the cache directory is corrupted. Essentially, I put a hard timeout to flush the cache directory if the connection does not connect. This has resolved the issue.

```
from retrying import retry
import signal
import glob

    @retry(stop_max_attempt_number=3, wait_exponential_multiplier=500)
    def get_snowflake_connection(self,
                                 user: str,
                                 account: str,
                                 private_key):
        """

        :param username:
        :param endpoint:
        :param private_key:
        :return:
        """
        # noinspection PyPackageRequirements
        import snowflake.connector
        # noinspection PyPackageRequirements
        import snowflake.connector.ocsp_snowflake
        snowflake_cache_directory = \
            snowflake.connector.ocsp_snowflake.OCSPCache.CACHE_DIR
        try:
            signal.signal(signal.SIGALRM, self.timeout_handler)
            signal.alarm(7)
            snowflake_ctx = snowflake.connector.connect(
                user=user,
                account=account,
                private_key=private_key
            )
            return snowflake_ctx
        except TimeoutError:
            print("Snowflake failed to connect. "
                  "This is likely due to a corrupt cache directory. "
                  "Deleting directory and retrying.")
            files = glob.glob(f"{snowflake_cache_directory}/*")
            for f in files:
                os.remove(f)

            raise ConnectionError("Unable to create a connection to Snowflake")
        finally:
            signal.alarm(0)
```

**Comment by sfc-gh-aling** [comment]
thanks @mbwmbw1337 for the detailed issue description and glad to know that you got a workaround for it.

I will re-open the issue for tracking such that any other people who might encounter the same issue could take a reference of your solution.

meanwhile we'll investigate and try to get it fixed asap.

**Comment by mbwmbw1337** [comment]
I was developing with intermittent internet, so it seems it may need to be the perfect storm of events to occur. I have tried manually corrupting the JSON files in the cache, but that didn't seem to do it. I wish I had backed up the infringing files before deleting them. The easiest solution might be if a method occurs on the authentication more than ten (10) times in a row to wipe the cache automagially. Note that this relates to #1325 in a "hard" timeout. I did try adjusting HTTP/login timeouts on the connect method but they still did timeout the authentication. 

I will keep trying to see if I can corrupt the files in a way to replace this issue.

**Comment by sfc-gh-aling** [comment]
we've found the root cause, it's a bug in our code that when there're expired entries in the OCSP cache dict, the code will try to clean up the expired ones, and then reload. However, reload again kicks off the cleaning up procedure, leading to infinite recursion.

I had a PR out for fix the issue: https://github.com/snowflakedb/snowflake-connector-python/pull/1348

really appreciate sharing us with the error stack which helps us to locate the issue easily.
We plan to do a bug fix release very soon. for now please either keep using the workaround you have or downgrade to 2.8.1.

**Comment by Smorasie** [comment]
> The issue was resolved by clearing the snowflake cache directory (/Users/michael/Library/Caches/Snowflake) -- I highly recommend that the showflake team build a fix for this into the system. The connection would not fail at all would stay open for hours.


[mbwmbw1337](https://github.com/mbwmbw1337) - Thank you! 
Was trying to resolve the issue for 3hrs.... Clearing the Cache folder made my day.

**Comment by mbwmbw1337** [comment]
> > The issue was resolved by clearing the snowflake cache directory (/Users/michael/Library/Caches/Snowflake) -- I highly recommend that the showflake team build a fix for this into the system. The connection would not fail at all would stay open for hours.
> 
> [mbwmbw1337](https://github.com/mbwmbw1337) - Thank you! Was trying to resolve the issue for 3hrs.... Clearing the Cache folder made my day.

Not a problem... I spent 12 hours on it myself and was ready to throw my laptop out my window... :).

**Comment by yuvanist** [comment]
> we've found the root cause, it's a bug in our code that when there're expired entries in the OCSP cache dict, the code will try to clean up the expired ones, and then reload. However, reload again kicks off the cleaning up procedure, leading to infinite recursion.
> 
> I had a PR out for fix the issue: #1348
> 
> really appreciate sharing us with the error stack which helps us to locate the issue easily. We plan to do a bug fix release very soon. for now please either keep using the workaround you have or downgrade to 2.8.1.

@sfc-gh-aling Hey, Can you share the estimated time for this bug fix release? and I'm still facing the same issue from main branch.

**Comment by mbwmbw1337** [comment]
> > we've found the root cause, it's a bug in our code that when there're expired entries in the OCSP cache dict, the code will try to clean up the expired ones, and then reload. However, reload again kicks off the cleaning up procedure, leading to infinite recursion.
> > I had a PR out for fix the issue: #1348
> > really appreciate sharing us with the error stack which helps us to locate the issue easily. We plan to do a bug fix release very soon. for now please either keep using the workaround you have or downgrade to 2.8.1.
> 
> @sfc-gh-aling Hey, Can you share the estimated time for this bug fix release?

Here's the latest I got... They're recommending rolling back to the prior version until they're able to get a release done.

```
Hello Michael,

Hope you are doing great!

We are releasing the fix for this issue in the next python connector version which is most probably 2.8.3. Until then, we would suggest you use 2.8.1. We will let you know once this version is released so that you can verify the same on your end.

Meanwhile, please let me know if you have any further questions on this support case.
```

**Comment by yuvanist** [comment]
Coo. Thanks, @mbwmbw1337. Much Appreciated.

**Comment by lijoabraham** [comment]
I was able to proceed by deleting the corrupted cache files from ` C:\Users\<respective user>\AppData\Local\Snowflake\Caches ` folder.

**Comment by mbwmbw1337** [comment]
> For Windows users, I was able to proceed by deleting the corrupted cache files from `C:\Users\<respective user>\AppData\Local\Snowflake\Caches` folder.

Thank you for adding.

**Comment by PvanHengel** [comment]
Hi thanks for this, after many hours of digging I too had this same issue, not sure how it started, what version of the python library will the fix be released in?

**Comment by mbwmbw1337** [comment]
> Hi thanks for this, after many hours of digging I too had this same issue, not sure how it started, what version of the python library will the fix be released in?

See the conversation chain above for details of how this occurred. It's a coding bug on Snowflake's side.

To answer the rest of your question: According to Snowflake this issue will be most probably fixed in 2.8.3. Downgrade to 2.8.1 for now.

**Comment by sfc-gh-aling** [comment]
hi folks, appreciate your understanding and patience.
we have just released v2.8.3 and yanked v2.8.2. please upgrade via command `pip install snowflake-connector-python --upgrade`.

please let me know if you still encounter the issue or need any other help.

**Comment by JacobHayes** [comment]
I think I'm still getting this with 2.8.3 (even after removing the cache dir):
```
$ pip3 freeze | grep snowflake-
snowflake-connector-python==2.8.3
snowflake-sqlalchemy==1.4.4
```
One other annoying part that it seems to _occasionally_ hang in some C(?) code that doesn't catch `KeyboardInterrupt`s/ctrl-c, so I have to `kill $PYTHON_PROC_PID`.

After downgrading back to 2.8.1 (and removing the cache dir again), it still seems to hang. Perhaps I'm seeing a different issue?

**Comment by mbwmbw1337** [comment]
> I think I'm still getting this with 2.8.3 (even after removing the cache dir):
> 
> ```
> $ pip3 freeze | grep snowflake-
> snowflake-connector-python==2.8.3
> snowflake-sqlalchemy==1.4.4
> ```
> 
> One other annoying part that it seems to _occasionally_ hang in some C(?) code that doesn't catch `KeyboardInterrupt`s/ctrl-c, so I have to `kill $PYTHON_PROC_PID`.
> 
> After downgrading back to 2.8.1 (and removing the cache dir again), it still seems to hang. Perhaps I'm seeing a different issue?

Would you post a full stack trace or as much as possible? Please follow the instructions here: [https://community.snowflake.com/s/article/How-to-generate-log-file-on-Snowflake-connectors](https://community.snowflake.com/s/article/How-to-generate-log-file-on-Snowflake-connectors) under the `Python Connector / SQLAlchemy` section.

If the issue is similar, I'd respond here and open another bug if different. I haven't had time to test the new version sufficiently.

**Comment by JacobHayes** [comment]
I didn't get a stacktrace until a ctrl-c or `kill`, it would just hang - poking around a bit more, perhaps it was https://github.com/snowflakedb/snowflake-connector-python/issues/1325 (I didn't actually wait 12m before). While trying to get the extra logging output, I did end up with 1 run over 12m (not sure exactly) and another that ran at the same time for the last couple minutes - after waiting the 12m, it seems to be working again... 😕

In case it's still useful, here is the other debug info:

> python --version

Python 3.10.2

> python -c 'import platform; print(platform.platform())'

macOS-12.5-x86_64-i386-64bit

> pip list

<details>
<summary>Output</summary>

```
Package                               Version      Editable project location
------------------------------------- ------------ ------------------------------------------------------------------------
aiobotocore                           2.4.1
aiohttp                               3.8.3
aioitertools                          0.11.0
aiosignal                             1.3.1
alembic                               1.8.1
altair                                4.2.0
antlr4-python3-runtime                4.9.3
anyio                                 3.6.2
appnope                               0.1.3
argo-workflows                        6.3.5
argon2-cffi                           21.3.0
argon2-cffi-bindings                  21.2.0
asn1crypto                            1.5.1
asttokens                             2.2.0
async-timeout                         4.0.2
attrs                                 22.1.0
Babel                                 2.11.0
backcall                              0.2.0
backoff                               1.11.1
beautifulsoup4                        4.11.1
biopython                             1.80
black                                 22.10.0
bleach                                5.0.1
bokeh                                 2.4.3
boto3                                 1.24.59
botocore                              1.27.59
build                                 0.9.0
cachetools                            5.2.0
certifi                               2022.9.24
cffi                                  1.15.1
charset-normalizer                    2.1.1
click                                 8.1.3
cloudpickle                           2.2.0
coiled                                0.2.50
coloredlogs                           15.0.1
comm                                  0.1.1
commonmark                            0.9.1
contourpy                             1.0.6
coverage                              6.5.0
cryptography                          38.0.4
cycler                                0.11.0
Cython                                0.29.32
cyvcf2                                0.30.18
dash                                  2.7.0
dash-bootstrap-components             1.2.1
dash-core-components                  2.0.0
dash-daq                              0.5.0
dash-html-components                  2.0.0
dash-table                            5.0.0
dask                                  2022.11.1
dask-labextension                     6.0.0
dask-snowflake                        0.2.0
dataclasses-json                      0.5.7
db-dtypes                             1.0.4
debugpy                               1.6.4
decorator                             5.1.1
defusedxml                            0.7.1
distributed                           2022.11.1
docutils                              0.19
editdistance                          0.6.2
entrypoints                           0.4
exceptiongroup                        1.0.4
execnet                               1.9.0
executing                             1.2.0
fastapi                               0.88.0
fastapi-restful                       0.4.3
fastjsonschema                        2.16.2
fastq-and-furious                     0.3.2
filelock                              3.8.0
flake8                                6.0.0
Flask                                 2.2.2
fonttools                             4.38.0
frozenlist                            1.3.3
fsspec                                2022.11.0
gcsfs                                 2022.11.0
google-api-core                       2.10.2
google-api-python-client              2.66.0
google-auth                           2.14.1
google-auth-httplib2                  0.1.0
google-auth-oauthlib                  0.7.1
google-cloud-bigquery                 3.4.0
google-cloud-bigquery-storage         2.16.2
google-cloud-core                     2.3.2
google-cloud-iam                      2.9.0
google-cloud-secret-manager           2.12.6
google-cloud-storage                  2.6.0
google-crc32c                         1.5.0
google-resumable-media                2.4.0
googleapis-common-protos              1.57.0
graphviz                              0.20.1
greenlet                              2.0.1
grpc-google-iam-v1                    0.12.4
grpcio                                1.51.1
grpcio-status                         1.48.2
gunicorn                              20.1.0
h11                                   0.14.0
HeapDict                              1.0.1
hera-workflows                        4.2.0
httpcore                              0.16.2
httplib2                              0.21.0
httptools                             0.5.0
httpx                                 0.23.1
humanfriendly                         10.0
idna                                  3.4
importlib-metadata                    4.13.0
iniconfig                             1.1.1
ipykernel                             6.18.3
ipython                               8.7.0
ipython-genutils                      0.2.0
ipywidgets                            7.7.2
isort                                 5.10.1
itsdangerous                          2.1.2
jaraco.classes                        3.2.3
jedi                                  0.18.2
Jinja2                                3.1.2
jmespath                              1.0.1
joblib                                1.2.0
json5                                 0.9.10
jsondiff                              2.0.0
jsonschema                            4.17.3
jupyter                               1.0.0
jupyter-client                        7.3.4
jupyter-console                       6.4.4
jupyter_core                          5.1.0
jupyter-server                        1.23.3
jupyter-server-proxy                  3.2.2
jupyterlab                            3.5.0
jupyterlab-pygments                   0.2.2
jupyterlab_server                     2.16.3
jupyterlab-widgets                    1.1.1
keyring                               23.11.0
keyrings.google-artifactregistry-auth 1.1.1
kiwisolver                            1.4.4
llvmlite                              0.39.1
locket                                1.0.0
Mako                                  1.2.4
MarkupSafe                            2.1.1
marshmallow                           3.19.0
marshmallow-enum                      1.5.1
matplotlib                            3.6.2
matplotlib-inline                     0.1.6
mccabe                                0.7.0
mistune                               2.0.4
more-itertools                        9.0.0
msgpack                               1.0.4
multidict                             6.0.2
mypy                                  0.991
mypy-extensions                       0.4.3
mysql-connector-python                8.0.31
nanoid                                2.0.0
nbclassic                             0.4.8
nbclient                              0.7.2
nbconvert                             7.2.5
nbformat                              5.7.0
nest-asyncio                          1.5.6
notebook                              6.5.2
notebook_shim                         0.2.2
numba                                 0.56.4
numpy                                 1.23.5
oauthlib                              3.2.2
omegaconf                             2.2.3
opt-einsum                            3.3.0
oscrypto                              1.3.0
packaging                             21.3
pandas                                1.5.2
pandas-gbq                            0.18.1
pandocfilters                         1.5.0
parasail                              1.3.3
parso                                 0.8.3
partd                                 1.3.0
pathspec                              0.10.2
patsy                                 0.5.3
pep517                                0.13.0
pexpect                               4.8.0
pickleshare                           0.7.5
Pillow                                9.3.0
pip                                   22.3.1
pkginfo                               1.9.2
platformdirs                          2.5.4
plotly                                5.11.0
plotly-calplot                        0.1.13
pluggy                                1.0.0
prometheus-client                     0.15.0
prompt-toolkit                        3.0.33
proto-plus                            1.22.1
protobuf                              3.19.6
psutil                                5.9.4
psycopg2-binary                       2.9.5
ptyprocess                            0.7.0
pure-eval                             0.2.2
py3Dmol                               1.8.1
pyarrow                               8.0.0
pyasn1                                0.4.8
pyasn1-modules                        0.2.8
pycodestyle                           2.10.0
pycparser                             2.21
pycryptodomex                         3.16.0
pydantic                              1.10.2
pydata-google-auth                    1.4.0
pyfarmhash                            0.3.2
pyflakes                              3.0.1
Pygments                              2.13.0
PyJWT                                 2.6.0
pynndescent                           0.5.8
pyOpenSSL                             22.1.0
pyparsing                             3.0.9
pyro-api                              0.1.2
pyro-ppl                              1.8.3
pyrsistent                            0.19.2
pysam                                 0.20.0
pytest                                7.2.0
pytest-cov                            4.0.0
pytest-sugar                          0.9.6
pytest-xdist                          3.0.2
python-dateutil                       2.8.2
python-dotenv                         0.21.0
pytz                                  2022.6
PyYAML                                6.0
pyzmq                                 24.0.1
qtconsole                             5.4.0
QtPy                                  2.3.0
readme-renderer                       37.3
regex                                 2022.10.31
requests                              2.28.1
requests-oauthlib                     1.3.1
requests-toolbelt                     0.10.1
returns                               0.19.0
rfc3986                               1.5.0
rich                                  12.6.0
rsa                                   4.9
rstr                                  3.2.0
s3fs                                  2022.11.0
s3transfer                            0.6.0
scikit-learn                          1.1.3
scipy                                 1.9.3
seaborn                               0.12.1
Send2Trash                            1.8.0
setuptools                            65.6.3
sh                                    1.14.3
simpervisor                           0.4
six                                   1.16.0
slack-sdk                             3.19.4
smart-open                            6.2.0
sniffio                               1.3.0
snowflake-connector-python            2.8.3
snowflake-sqlalchemy                  1.4.4
sortedcontainers                      2.4.0
soupsieve                             2.3.2.post1
SQLAlchemy                            1.4.44
stack-data                            0.6.2
starlette                             0.22.0
statsmodels                           0.13.5
tblib                                 1.7.0
tenacity                              8.1.0
termcolor                             2.1.1
terminado                             0.17.0
textual                               0.5.0
threadpoolctl                         3.1.0
tinycss2                              1.2.1
tomli                                 2.0.1
toolz                                 0.12.0
torch                                 1.12.1
tornado                               6.1
tqdm                                  4.64.1
traitlets                             5.6.0
twine                                 4.0.1
types-PyYAML                          6.0.12.2
types-regex                           2022.10.31.3
types-requests                        2.28.11.5
types-urllib3                         1.26.25.4
typing_extensions                     4.4.0
typing-inspect                        0.8.0
umap-learn                            0.5.3
uplink                                0.9.7
uritemplate                           4.1.1
urllib3                               1.26.13
uvicorn                               0.20.0
uvloop                                0.17.0
watchfiles                            0.18.1
wcwidth                               0.2.5
webencodings                          0.5.1
websocket-client                      1.4.2
websockets                            10.4
Werkzeug                              2.2.2
wheel                                 0.37.1
widgetsnbextension                    3.6.1
wrapt                                 1.14.1
xyzservices                           2022.9.0
yarl                                  1.8.1
zict                                  2.2.0
zipp                                  3.11.0
```

</details>

**Comment by bneelon85** [comment]
So glad I found this issue. I thought I was going crazy. New ETL scripts were running fine for a few days and then kept taking down the server once it maxxed out the memory for no good reason.

So far so good with 2.8.3...

**Comment by sfc-gh-aling** [comment]
hey @JacobHayes, I think your case would be a different issue, because the issue discussed here is not causing hang, it causes `RecursionError` and crashes the program.

please feel free to open a new github issue and share more details with us on your scripts, your running env, loggings, etc. or you could append comments to the issue #1325 if you feel they're similar.

**Comment by voyera** [comment]
For people using ubuntu the cache folder is here: `~/.cache/snowflake`

This worked great for me as a temporary solution... I was going crazy spinning up new vms because I thought the linux networking was broken!

**Comment by sfc-gh-aling** [comment]
hey @voyera , may I ask which version are you using? we have released v2.8.3 to fix the issue and yanked v2.8.2.
are you still observing the issue after upgrading to v2.8.3?

**Comment by voyera** [comment]
@sfc-gh-aling I cleared my cache and upgraded to v2.8.3 as well... the weird thing for me is that it would happen after 24h of usage. I will monitor for a few days to see if it's repaired :)

**Comment by sfc-gh-aling** [comment]
@voyera let's keep it running for 24h and let me know how it goes, thanks!

**Comment by sfc-gh-achandrasekaran** [comment]
@voyera How are things looking with this issue?

**Comment by mbwmbw1337** [comment]
All resolved from my end.

**Comment by yuvanist** [comment]
Same here. Can close this safely. Resolved from my side as well.
