### ISSUE TITLE
SNOW-139744: restrictive dependencies breaking projects

### ISSUE THREAD

**Issue by serpiko** [snowflakedb/snowflake-connector-python#281]
Problem with python3.6 and python3.7 running on debian like and centos7 

Your setup.py has this definition limiting the versions of some mainstream packages like requests and idna:

    install_requires=[
...
        'requests<2.23.0',
        'idna<2.9'
...

It makes really hard to depend upon snowflake-connector-python since it's going to break any deployment as soon as you start using other library that also uses requests or idna ( this is very frequent in the python universe nowadays )

**Comment by keller00** [comment]
Hi @serpiko the new version of `idna` has failed our internal testing.
We try to keep on top of dependency releases, but pinning dependencies makes sure that we keep most customers happy by not breaking their environments and keeping their connector working.
If you really feel restricted by our release speed, I'd encourage you to fork the repository, test it yourself and then let us know if something doesn't work as expected.

Let's keep this ticket open to track the update to the newest release of `idna`, the new `requests` version seems to only update to the newest release of `idna` so they can be updated at the same time.

**Comment by serpiko** [comment]
Thanks @keller00  for the quick reply, I already forked (https://github.com/serpiko/snowflake-connector-python) but I prefer staying with the official connector.
sure, I'll stay tunned , 
thx, regards

**Comment by bastienboutonnet** [comment]
I agree with @serpiko on staying with the official connector, forking is really an ugly thing to have to do.

**Comment by keller00** [comment]
Sorry, not sure why I closed this.

**Comment by optroodt** [comment]
Specifically regarding `requests`, since it uses [semver](https://semver.org/#summary), why don't you relax the requirements a bit like `requests>=2.23.0,<3.0.0`. Minor version updates should only add functionality in a backwards compatible way, so all is good.

It actually makes more sense than the `requests<2.23.0` requirement, which implies `snowflake-connector-python` would work with `requests==1.0.0`, which is probably not true (although I haven't tested this :)).

We use `snowflake-connector-python` as part of a bigger project and these restrictive requirements are a bit of a nuisance.

**Comment by manugarri** [comment]
i wrote a similar issue some weeks ago. https://github.com/snowflakedb/snowflake-connector-python/issues/284

**Comment by keller00** [comment]
We released the new version yesterday. It supports the newer versions. Going to close this for now.

**Comment by manugarri** [comment]
@keller00 what does that mean, that the issues with dependencies are fixed?

**Comment by optroodt** [comment]
The updated requirements still don't make a lot of sense. For example `botocore>=1.5.0,<1.15`, this means I'm stuck with a minor version (`1.14.*`) that's not the latest. It's a month old, the most current version is `1.15.19`.

It seems that the `snowflake-connector-python` project follows semver, why not apply the same logic to your requirements?

**Comment by avikaps** [comment]
I'm still facing issues while deployit on Google Cloud functions as the Cloud Functions VM has the pre-installed with the listed packages : https://cloud.google.com/functions/docs/writing/specifying-dependencies-python
But the requests==2.24.0 is causing this issues the the dependency in the build id still 'requests<2.24.0'
Below is the traceback log 
File "/env/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve raise VersionConflict(dist, req).with_context(dependent_req) pkg_resources.ContextualVersionConflict: (requests 2.24.0 (/env/lib/python3.7/site-packages), Requirement.parse('requests<2.24.0'), {'snowflake-connector-python'})
Could you please fix this soon ?

**Comment by johnrhageman** [comment]
I am experiencing the exact same issue: 

{"Error": "Failed to run Snowflake job: (requests 2.24.0 (/env/lib/python3.7/site-packages), Requirement.parse('requests<2.24.0'), {'snowflake-connector-python'})"}

This is preventing us from deploying projects to production ATM.

**Comment by JMKeskinen** [comment]
I'm having same issue..

**Comment by bisaacsdfs** [comment]
I'm having the same issue :
ContextualVersionConflict: (requests 2.24.0 (env\lib\site-packages), Requirement.parse('requests<2.24.0'), {'snowflake-connector-python'})

"Resolved" by downgrading `requests ` to 2.23.0
